# Generated by Django 5.2 on 2025-04-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='warehouse_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_code',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='Warehouses',
        ),
    ]
