# Generated by Django 5.2 on 2025-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_warehouse_name_warehouse_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
