# Generated by Django 5.2 on 2025-04-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_created_at_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
