# Generated by Django 5.2 on 2025-04-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_productwarehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productwarehouse',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productwarehouse',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
    ]
