# Generated by Django 5.2 on 2025-04-13 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_product_id_productwarehouse_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productwarehouse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='productwarehouse',
            unique_together={('product', 'warehouse')},
        ),
    ]
