# Generated by Django 5.2 on 2025-04-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_productwarehouse_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(related_name='products', through='api.ProductWarehouse', to='api.warehouse'),
        ),
    ]
