# Generated by Django 5.2 on 2025-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_warehouse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantities',
            field=models.JSONField(default=dict),
        ),
    ]
