# Generated by Django 5.2 on 2025-04-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_product_quantities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantities',
            new_name='quantity_selected',
        ),
    ]
