# Generated by Django 5.2 on 2025-04-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_quantities_product_quantity_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_selected',
            new_name='quantity_yyyy_mm_dd',
        ),
    ]
