# Generated by Django 5.2 on 2025-04-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_quantity_selected_product_quantity_yyyy_mm_dd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_yyyy_mm_dd',
        ),
    ]
