# Generated by Django 5.2 on 2025-04-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_productstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='productstock',
            table='product_stocks',
        ),
    ]
