# Generated by Django 5.2 on 2025-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_productstock_quantity_alter_productstock_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPrevDateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
