# Generated by Django 5.2 on 2025-04-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_showprevdatesetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowPrevDateSetting',
            new_name='ShowSetting',
        ),
    ]
