# Generated by Django 5.2 on 2025-04-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_showprevdatesetting_showsetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowSetting',
            new_name='ShowPrevDateSetting',
        ),
    ]
