# Generated by Django 5.2 on 2025-04-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_permission_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
