# Generated by Django 5.2 on 2025-04-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_userpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
