# Generated by Django 5.2 on 2025-04-22 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_delete_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='RoleCreationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can_create_roles', to='api.role')),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatable_by_roles', to='api.role')),
            ],
            options={
                'unique_together': {('creator_role', 'target_role')},
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
