# Generated by Django 5.2 on 2025-04-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_role_role_rolecreationrule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermissionoverride',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpermissionoverride',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userpermissionoverride',
            name='user',
        ),
        migrations.DeleteModel(
            name='RoleCreationRule',
        ),
        migrations.DeleteModel(
            name='UserPermissionOverride',
        ),
    ]
