# Generated by Django 5.2 on 2025-04-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
