# Generated by Django 5.2 on 2025-04-23 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_userpermission_is_removed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.CreateModel(
            name='PermissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permission')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permission_assignments',
                'unique_together': {('user', 'role', 'permission')},
            },
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
