# Generated by Django 5.2 on 2025-04-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_userpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionassignment',
            name='allow',
            field=models.BooleanField(default=True),
        ),
    ]
