# Generated by Django 5.2 on 2025-05-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_product_company_product_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productstock',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='api.company'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'warehouse', 'date', 'company')},
        ),
    ]
