# Generated by Django 5.2 on 2025-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_productstock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
