# Generated by Django 5.2.1 on 2025-06-23 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_savedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='api.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='savedreport',
            unique_together={('name', 'company')},
        ),
        migrations.AlterModelTable(
            name='savedreport',
            table='saved_report',
        ),
    ]
