# Generated by Django 5.2.1 on 2025-06-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_savedreport_company_savedreport_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedreport',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='savedreport',
            table=None,
        ),
        migrations.RemoveField(
            model_name='savedreport',
            name='company',
        ),
        migrations.RemoveField(
            model_name='savedreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='savedreport',
            name='updated_at',
        ),
    ]
