# Generated by Django 5.2.1 on 2025-06-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_savedreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
