# Generated by Django 5.2.1 on 2025-07-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_savedreport_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='column_values',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='row_values',
            field=models.JSONField(default=list),
        ),
    ]
