# Generated by Django 5.2.1 on 2025-07-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_savedreport_column_values_savedreport_row_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='filter_values',
            field=models.JSONField(default=dict),
        ),
    ]
